name: xurumin-ci
on:
  push:
    branches:
      - phoenix
  pull_request:
    branches:
      - phoenix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          version: latest
      - run: bun install
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          COMMAND_PREFIX: ${{ secrets.COMMAND_PREFIX }}

      - uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

